### ISSUE TITLE
Language repo clone should be recursive

### ISSUE THREAD

**Issue by jskeet** [googleapis/generator#28]
Just found this when running the .NET tests - we have a submodule for conformance tests. When it's not cloned, the relevant tests fail.
Other languages may have submodules for other reasons.

We probably *don't* need this for googleapis.

**Comment by jskeet** [comment]
This should just be a matter of adding the equivalent of "--recursive" when cloning.

**Comment by burkedavison** [comment]
Once the generator is performing the clone, this should be resolved with the existing configuration:
https://github.com/googleapis/generator/blob/main/internal/gitrepo/gitrepo.go#L64-L66

**Comment by jskeet** [comment]
We're now doing the clone, and I can confirm this is fine.
